test/support/my_app/test/support/conn_case.ex:1: Unknown function 'Elixir.ExUnit.Callbacks':'__merge__'/4
test/support/my_app/test/support/conn_case.ex:1: Unknown function 'Elixir.ExUnit.Callbacks':'__noop__'/0
test/support/my_app/test/support/conn_case.ex:20: Unknown function 'Elixir.ExUnit.CaseTemplate':'__proxy__'/2
